#!/bin/sh
set -eu

docker run --rm \
	-v "$(pwd):$(pwd)" \
	-w "$(pwd)" \
	-u "$(id -u):$(id -g)" \
	-e npm_config_cache="$(pwd)/.npm-cache" \
	node:24-alpine \
	sh -c "npm install --no-save @vercel/ncc && npm run build-dist"
