# https://github.com/marketplace/actions/publish-docker

name: Publish to Docker
on:
  push:
  pull_request:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:
  prepare-versions:
    name:               "List perl versions"
    runs-on:            ubuntu-latest
    outputs:
      bookworm:  ${{ steps.action.outputs.versions-target-perl-bookworm }}
      buster:    ${{ steps.action.outputs.versions-target-perl-buster }}
      trixie:    ${{ steps.action.outputs.versions-target-perl-trixie }}
    steps:
      - id:             action
        name:           Perl versions action step
        uses:           perl-actions/multi-target-perl-versions@v2
        with:
          since-perl:                '5.8'
          with-target-perl-bookworm: 'true'
          with-target-perl-bullseye: 'false'
          with-target-perl-buster:   'true'
          with-target-perl-trixie:   'true'

  prepare-matrix:
    name:               "Prepare matrix"
    runs-on:            ubuntu-latest
    needs:
      - prepare-versions
    outputs:
      matrix:           ${{ steps.action.outputs.matrix }}
    steps:
      - uses:           actions/checkout@v6
      - id:             action
        name:           "Perl versions action step"
        uses:           ./.github/actions/build-matrix
        with:
          bookworm:     ${{ needs.prepare-versions.outputs.bookworm }}
          buster:       ${{ needs.prepare-versions.outputs.buster   }}
          trixie:       ${{ needs.prepare-versions.outputs.trixie   }}

  latest-build:
    name: "Build latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian-version: [buster,slim-bookworm,slim-trixie]

    steps:
      - uses:           actions/checkout@v7
      - uses:           ./.github/actions/publish-docker
        with:
          hub-password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          hub-username: ${{ secrets.DOCKER_USERNAME }}
          base:         ${{ matrix.debian-version }}
          tags:         "latest,${{ matrix.debian-version }}"

  devel-build:
    name: "Build devel"
    runs-on: ubuntu-latest

    steps:
      - uses:           actions/checkout@v7
      - uses:           ./.github/actions/publish-docker
        with:
          hub-username: ${{ secrets.DOCKER_USERNAME }}
          hub-password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          base:         "devel-slim-bookworm"
          tags:         "devel,devel-slim-bookworm"

  dump-matrix:
    name:               "Dump matrix"
    runs-on:            ubuntu-latest
    needs:
      - prepare-matrix
    steps:
      - shell:          "bash"
        env:
          MATRIX:       ${{ toJSON (fromJSON (needs.prepare-matrix.outputs.matrix)) }}
        run:            'echo "$MATRIX"'


  build:
    name:               "Build and publish docker images"
    runs-on:            ubuntu-latest
    needs:
      - prepare-matrix

    strategy:
      fail-fast:        false
      matrix:           ${{ fromJSON (needs.prepare-matrix.outputs.matrix) }}

    steps:
      - uses:           actions/checkout@v7
      - name:           "Build and Publish to Registry: ${{ matrix.base }} => ${{ matrix.tags }}"
        uses:           ./.github/actions/publish-docker
        with:
          hub-username: ${{ secrets.DOCKER_USERNAME }}
          hub-password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          base:         ${{ matrix.base }}
          tags:         ${{ matrix.tags }}
